services:
  postgresdb:
    image: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    environment:
      POSTGRES_USER:  "${DB_USER}"
      POSTGRES_PASSWORD:  "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: