version: '3'
services:
  postgresdb:
    image: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: farmacia-tech-db
    ports:
      - "5432:5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data