BEGIN;
CREATE TABLE IF NOT EXISTS Delivery (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  reference TEXT NOT NULL,
  client_id BIGINT NOT NULL,
  medicine_id BIGINT NOT NULL,
  qty INT NOT NULL,
  unit_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ
);
COMMIT;