name: Go CI

on:
  pull_request:
    branches: [ "main" ]
    paths: ["**.go", "go.mod", "go.sum"]

jobs:
  lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.59.0
          args: --timeout 3m